# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
            -   id: check-ast
            -   id: check-case-conflict
            -   id: check-json
            -   id: check-merge-conflict
            -   id: check-yaml
                args: [--unsafe]
            -   id: debug-statements
            -   id: end-of-file-fixer
            -   id: fix-encoding-pragma
            -   id: mixed-line-ending
            -   id: requirements-txt-fixer
            -   id: trailing-whitespace
    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.14.13  # same as in pyproject.toml
        hooks:
            # linter
            - id: ruff-check
              args: [ --fix ]
            # formatter
            - id: ruff-format
