# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools>=65.5.0', 'wheel']

[project]
authors = [
    {name = 'Stefano Ubbiali', email = 'subbiali@phys.ethz.ch'},
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Science/Research',
    'Operating System :: POSIX',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
]
dependencies = [
    'click',
    'fmodpy',
    'gt4py[dace] @ git+https://github.com/GridTools/gt4py.git@2cd0c91',  # same as ifs_physics_common
    'h5py>=3.0',
    'ifs_physics_common @ git+https://github.com/stubbiali/ifs-physics-common.git@v0.2.0',
    'jinja2',
    'netcdf4',
    'numpy>=1.21,<2.0',
    'pydantic<2.0',
]
description = 'A Python framework to validate multiple implementations of stencil kernels.'
keywords = ['fortran', 'python', 'stencils', 'validation']
license = {text = 'Apache-2'}
name = 'stencil_validation'
readme = {file = 'README.md', content-type = 'text/markdown'}
requires-python = '>=3.8'
version = '0.0'

[project.optional-dependencies]
dev = [
    'black==24.4.0',  # note(stubbiali): coherent with corresponding pre-commit hook
    'flake8',
    'ipdb',
    'ipython==8.22.0',  # note(stubbiali): required to make ipdb work
    'mypy',
    'pre-commit',
]
test = ['pytest']

[project.scripts]
iodiff = 'stencil_validation.validation:compare_io_files'

[project.urls]
Source = 'https://github.com/stubbiali/stencil-validation.git'

# === black
[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.gt_cache
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''
skip-magic-trailing-comma = true

# === mypy
[tool.mypy]
check_untyped_defs = true
# set to `true` once cupy support typing
disallow_any_unimported = false
disallow_incomplete_defs = true
disallow_untyped_defs = true
exclude = []
implicit_optional = false
install_types = true
plugins = 'numpy.typing.mypy_plugin'
show_column_numbers = true
show_error_codes = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = 'h5py'
ignore_missing_imports = true

[tool.setuptools]
platforms = ['Linux', 'Mac']

[tool.setuptools.package-data]
'stencil_validation' = ['py.typed']

[tool.setuptools.packages]
find = {namespaces = false, where = ['src']}
